"""add_is_pinned_to_chat_session

Revision ID: 31711b29eee9
Revises: a917f3b7d2e1
Create Date: 2026-08-23 15:57:58.910715

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31711b29eee9'
down_revision: Union[str, Sequence[str], None] = 'a917f3b7d2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default='false'))
    op.alter_column('travel_package', 'flight_info',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('travel_package', 'flight_info',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('chat_session', 'is_pinned')
    # ### end Alembic commands ###
