"""add_booking_info_to_travel_package

Revision ID: 597600d82595
Revises: b74d75045238
Create Date: 2026-08-26 15:43:14.723730

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '597600d82595'
down_revision: Union[str, Sequence[str], None] = 'b74d75045238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_package', sa.Column('booking_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_package', 'booking_info')
    # ### end Alembic commands ###
