"""add_cascade_deletes

Revision ID: 6b5d796b0d3d
Revises: 1ec9d55e0b29
Create Date: 2026-07-31 09:52:29.421504

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5d796b0d3d'
down_revision: Union[str, Sequence[str], None] = '1ec9d55e0b29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_message_chat_session_id_fkey'), 'chat_message', type_='foreignkey')
    op.create_foreign_key(None, 'chat_message', 'chat_session', ['chat_session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chat_session_owner_id_fkey'), 'chat_session', type_='foreignkey')
    op.create_foreign_key(None, 'chat_session', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('search_history_search_session_id_fkey'), 'search_history', type_='foreignkey')
    op.create_foreign_key(None, 'search_history', 'search_session', ['search_session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('search_session_owner_id_fkey'), 'search_session', type_='foreignkey')
    op.create_foreign_key(None, 'search_session', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_session', type_='foreignkey')
    op.create_foreign_key(op.f('search_session_owner_id_fkey'), 'search_session', 'user', ['owner_id'], ['id'])
    op.drop_constraint(None, 'search_history', type_='foreignkey')
    op.create_foreign_key(op.f('search_history_search_session_id_fkey'), 'search_history', 'search_session', ['search_session_id'], ['id'])
    op.drop_constraint(None, 'chat_session', type_='foreignkey')
    op.create_foreign_key(op.f('chat_session_owner_id_fkey'), 'chat_session', 'user', ['owner_id'], ['id'])
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.create_foreign_key(op.f('chat_message_chat_session_id_fkey'), 'chat_message', 'chat_session', ['chat_session_id'], ['id'])
    # ### end Alembic commands ###
