"""add_monthly_messages_used

Revision ID: 990b9b447981
Revises: e85827c3c5b7
Create Date: 2026-08-27 14:45:20.319558

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990b9b447981'
down_revision: Union[str, Sequence[str], None] = 'e85827c3c5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('monthly_messages_used', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'monthly_messages_used')
    # ### end Alembic commands ###
