"""add_stripe_subscription_fields

Revision ID: b74d75045238
Revises: 31711b29eee9
Create Date: 2026-08-25 19:27:46.759872

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74d75045238'
down_revision: Union[str, Sequence[str], None] = '31711b29eee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('stripe_subscription_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('user', sa.Column('subscription_cancel_at_period_end', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('subscription_current_period_end', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'subscription_current_period_end')
    op.drop_column('user', 'subscription_cancel_at_period_end')
    op.drop_column('user', 'stripe_subscription_id')
    op.drop_column('user', 'stripe_customer_id')
    # ### end Alembic commands ###
