"""add_destination_photos_to_travel_package

Revision ID: e85827c3c5b7
Revises: 597600d82595
Create Date: 2026-08-27 13:27:40.178786

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e85827c3c5b7'
down_revision: Union[str, Sequence[str], None] = '597600d82595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel_package', sa.Column('destination_photos', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_package', 'destination_photos')
    # ### end Alembic commands ###
