"""add_has_seen_onboarding

Revision ID: fc24ce325744
Revises: 990b9b447981
Create Date: 2026-08-30 21:02:33.040554

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc24ce325744'
down_revision: Union[str, Sequence[str], None] = '990b9b447981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_seen_onboarding', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_seen_onboarding')
    # ### end Alembic commands ###
